version: '3.9'

services:
  server:
    build: .
    container_name: perfumeshop-server
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/mydb
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:16
    container_name: request-track
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
